project_id = "qzqezldtklimtupajvxf"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://greenacreeaglesfc.com"
additional_redirect_urls = [
  "https://greenacreeaglesfc.com/auth/confirm",
  "https://greenacreeaglesfc.com/reset-password",
  "http://localhost:4321/auth/confirm",
  "http://localhost:4321/reset-password"
]

[db]
major_version = 17

[auth.email.template.recovery]
subject = "Reset your Greenacre Eagles FC password"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.confirmation]
subject = "Confirm your Greenacre Eagles FC account"
content_path = "./supabase/templates/confirmation.html"
