import type { APIRoute } from "astro";
import { z } from "zod";
import { requirePermission } from "@lib/auth/guards";
import { redirectWithMessage } from "@lib/forms";
export const prerender=false;
const nullable=(max:number)=>z.preprocess(v=>v===""?null:v,z.string().trim().max(max).nullable());const optionalDate=z.preprocess(v=>v===""?null:v,z.string().nullable());const checkbox=z.preprocess(v=>v==="on"||v==="true",z.boolean());const dollars=z.preprocess(v=>v===""?null:Math.round(Number(v)*100),z.number().int().min(0).nullable());
const productSchema=z.object({name:z.string().trim().min(2).max(160),description:nullable(800),category:nullable(100),image_url:nullable(300),status:z.enum(["active","inactive"]),featured:checkbox,sort_order:z.coerce.number().int().min(0).max(10000),available_from:optionalDate,available_until:optionalDate});
const variantSchema=z.object({product_id:z.string().uuid(),sku:nullable(80),size:nullable(40),colour:nullable(80),price:dollars.refine(v=>v!==null,"Price is required."),sale_price:dollars,stock_quantity:z.coerce.number().int().min(0).max(999999),low_stock_threshold:z.coerce.number().int().min(0).max(999999),is_active:checkbox});
export const POST:APIRoute=async context=>{const session=await requirePermission(context,["merchandise.manage"]);if(!session)return context.redirect("/admin/");const form=Object.fromEntries(await context.request.formData());const entity=form.entity==="variant"?"variant":"product";const table=entity==="variant"?"merchandise_variants":"merchandise_products";const id=z.string().uuid().safeParse(form.id);if(form.intent==="delete"){if(!id.success)return context.redirect(redirectWithMessage("/admin/merchandise/","error","Invalid merchandise record."));const{error}=await(session.supabase as any).from(table).delete().eq("id",id.data);return context.redirect(redirectWithMessage("/admin/merchandise/",error?"error":"success",error?.message??(entity==="variant"?"Variant deleted.":"Product deleted.")));}const parsed=(entity==="variant"?variantSchema:productSchema).safeParse(form);if(!parsed.success)return context.redirect(redirectWithMessage("/admin/merchandise/","error",parsed.error.issues[0]?.message??"Check the merchandise details."));let values:Record<string,unknown>;if(entity==="variant"){const{price,sale_price,...data}=parsed.data as z.infer<typeof variantSchema>;values={...data,price_cents:price,sale_price_cents:sale_price};}else values=parsed.data as z.infer<typeof productSchema>;const result=id.success?await(session.supabase as any).from(table).update(values).eq("id",id.data):await(session.supabase as any).from(table).insert(values);const message=result.error?.code==="23505"?"That SKU is already in use.":result.error?.message;return context.redirect(redirectWithMessage("/admin/merchandise/",result.error?"error":"success",message??(entity==="variant"?"Variant saved.":"Product saved.")));};
